ConnectApp/Controllers/SubjectsController.cs
using ConnectApp;
using ConnectApp.Models;
using DevExpress.XtraReports.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConnectApp.Controllers
{
    public class SubjectsController : BaseController
    {
        ConnectDBEntities db = new ConnectDBEntities();
        // GET: Subjects
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ReportViewPartial(string reportParams)
        {

            // var report = GetReport(reportParams);

            //return PartialView("ReportViewPartial", report);
            return null;
        }

        public ActionResult TurtorialsLanding(string headerObjId)
        {
            var mymodel = db.LanguageBases;
            var ApplicationsInfo = mymodel.Where(s => s.ObjId.ToString() == headerObjId).FirstOrDefault();

            ViewBag.TopicLink = ApplicationsInfo.Link;
            return PartialView("TurtorialsLanding");
        }
        //XtraReport GetReport(string passed_params)
        //{
        //    List<string> p = passed_params.Split(',').ToList();
        //    var rep = new StudentsReportXrMvc();
        //    rep.ObjId.Value = p[0];
        //    rep.Attention.Value = p[1];
        //  //  rep.FromDate.Value = p[2];
        //    //rep.ToDate.Value = p[4];
        //    return rep;
        //}

        private List<Language> GetLanguages()
        {
            return db.Languages.ToList();
        }

        private List<LanguagesDto> GetLanguagesDto()
        {
            var lang = db.Languages.ToList();
            var repo = db.LanguageBases.ToList();

            var model = (from lan in repo
                         from rpLang in  lang.Where(c => c.ObjId == lan.LangauageId).DefaultIfEmpty()
                         select new LanguagesDto
                         {
                             ObjId = lan.ObjId,
                             LanguageId = lan.LangauageId,
                             LanguageName = rpLang.Name,
                             Description = lan.Description,
                             Link = lan.Link
                         });

            return model.ToList();
        }
        public ActionResult EditHeaderFormPartial(Guid ObjId, LanguagesDto model)
		{
            ViewData["Languages"] = GetLanguages();

            var mymodel = GetLanguagesDto();

            var ApplicationsInfo = mymodel.Where(s => s.ObjId == ObjId).FirstOrDefault();

			if (ApplicationsInfo == null)
			{
				model.ObjId = ObjId;
				return PartialView("CreateSubjectsEditPartial", model);
			}

			if (ApplicationsInfo != null)
			{
                return PartialView("CreateSubjectsEditPartial", ApplicationsInfo);
			}

			return null;

		}      
    
        public ActionResult SubjectsAddEdit(LanguagesDto item, string headerObjId)
        {
  
            var modelRepo = db.LanguageBases;
            var exists = modelRepo.Where(c => c.ObjId == item.ObjId).SingleOrDefault();
            LanguageBase Tosave = new LanguageBase();
            Tosave.LangauageId = item.LanguageId;
            if (exists == null)
            {
                CopyProperties(item, Tosave);
             
                modelRepo.Add(Tosave);
                db.SaveChanges();
            }
            if (exists != null)
            {
                CopyProperties(item, exists);
                this.UpdateModel(exists);
                // modelRepo.Attach(exists);
                db.SaveChanges();
            }

            var BurialRecords = GetLanguagesDto();
            // DXCOMMENT: Pass a data model for GridView in the PartialView method's second parameter
            return PartialView("_SubjectsGridViewPartial", BurialRecords);

        }
       [HttpPost, ValidateInput(false)]
        public ActionResult SubjectsDelete(Guid ObjId)
        {
            var model = db.LanguageBases;
            if (ObjId != null)
            {
                try
                {
                    var item = model.FirstOrDefault(it => it.ObjId == ObjId);
                    if (item != null)
                    {
                        model.Remove(item);

                    }

                    db.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            var BurialRecords = GetLanguagesDto();
            // DXCOMMENT: Pass a data model for GridView in the PartialView method's second parameter
            return PartialView("_SubjectsGridViewPartial", BurialRecords);
        }
        public ActionResult SubjectsGridViewPartial()
        {
          //  var model = db.Lunguages;
            var mymodel = GetLanguagesDto();
            // DXCOMMENT: Pass a data model for GridView in the PartialView method's second parameter
            return PartialView("_SubjectsGridViewPartial", GetLanguagesDto().OrderBy(r => r.Description));
        }
    }
}

ConnectApp/Views/Subjects/CreateSubjectsEditPartial.cshtml
@using DevExpress.Web;
@using DevExpress.Web.Mvc;
@using ConnectApp.Models;

@model ConnectApp.Models.LanguagesDto

@Html.HiddenFor(e => e.ObjId)
@*@Html.HiddenFor(e => e.RoleId)*@



@Html.DevExpress().FormLayout(settings =>
{
    // Get Fields
    settings.Name = "formLanguage";

    var infoGroupItem1 = settings.Items.AddGroupItem(Gsettings =>
    {
        Gsettings.Caption = "Language Section";
        Gsettings.RowSpan = 4;
        Gsettings.ShowCaption = DefaultBoolean.True;
        Gsettings.ColCount = 1;


        Gsettings.Items.Add(e => e.LanguageId, itemSettings =>
        {
            itemSettings.FieldName = "LanguageDropDown";
            itemSettings.Caption = "Languages";
            itemSettings.SetNestedContent(() =>
            {

                @Html.DevExpress().ComboBox(ComboBoxsettings =>
                {
                    // Gsettings.Name = "Id";
                    ComboBoxsettings.Name = "LanguageId";
                    //  ComboBoxsettings.Width = 500;
                    ComboBoxsettings.SelectedIndex = 1;
                    ComboBoxsettings.Properties.TextField = "Name";
                    ComboBoxsettings.Properties.ValueField = "ObjId";
                    ComboBoxsettings.Properties.DropDownStyle = DropDownStyle.DropDown;
                    ComboBoxsettings.ShowModelErrors = true;
                }
          ).BindList(ViewData["Languages"]).Render();
            });

        });

        Gsettings.Items.Add(e => e.Description, itemSettings =>
        {
            itemSettings.Caption = "Description";
        });


        Gsettings.Items.Add(i => i.Link, itemSettings =>
        {
            itemSettings.Caption = "Link";
        });

        #region Buttons


        Gsettings.Items.Add(Buttonsettings =>
        {
            Buttonsettings.ShowCaption = DefaultBoolean.False;
            Buttonsettings.SetNestedContent(() =>
            {
                Html.ViewContext.Writer.Write("<div style='float:right'>");
                Html.DevExpress().Button(btnSettings =>
                {
                    btnSettings.Name = "btnSave";
                    btnSettings.Text = "Save";
                    btnSettings.ClientSideEvents.Click = "SaveSubject";
                }).Render();

                Html.DevExpress().Button(btnSettings =>
                {
                    btnSettings.Name = "btnCancel";
                    btnSettings.Text = "Cancel";
                    btnSettings.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
                    btnSettings.ClientSideEvents.Click = "function (s,e) {SubjectsGridViewPartial.CancelEdit();}";
                    btnSettings.UseSubmitBehavior = true;
                }).Render();

                Html.ViewContext.Writer.Write("</div>");

            });
        });
        #endregion

    });

}).GetHtml()

ConnectApp/Views/Subjects/Index.cshtml
@using (Html.BeginForm())
{
    <script type="text/javascript">

        function OnSubjectsHeaderGridFocusedRowChanged(s, e) {

            //Get the User's Id from the selected row
            s.GetRowValues(s.GetFocusedRowIndex(), 'ObjId', OnGetRowValues);
        }

        function OnGetRowValues(values) {
            //return the selected value
            Subjects_ObjId = values;
         //   TopicExamsGridViewPartial.PerformCallback();
        }

        function OnBeginCallback(s, e) {
            // alert('OnBeginCallback e:  ' + e);
            e.customArgs["headerObjId"] = Subjects_ObjId;
        }


        function InitialSetFocus(s, e) {
            if (s.GetFocusedRowIndex() < 0)
                s.SetFocusedRowIndex(0);
        }

        function HighlightEllipsis() {
            $('.dxgv.dx-ellipsis').each(function (i, elem) {
                var color = elem.offsetWidth < elem.scrollWidth ? '#FFF2C0' : 'white';
                elem.style.transition = 'background 1s';
                elem.style['background-color'] = color;
            });
        }

        //for exports on grids
        function OnToolbarItemClick(s, e) {
        }
        function IsExportToolbarCommand(command) {
            return command == "Pdf" || command == "Xlsx" || command == "Xls";
        }
        

        function SaveSubjectExam() {

            TopicExamsGridViewPartial.UpdateEdit()
        }
        function SaveSubject() {

        SubjectsGridViewPartial.UpdateEdit()
        }

        function PrintReport() {
            //Get Header
            var ObjId = SubjectsGridViewPartial.GetRowKey(SubjectsGridViewPartial.GetFocusedRowIndex());
            //Get values
            var attention = Attention.GetValue();
            //var datefrom = DateFrom.GetValue();
            //var dateto = DateTo.GetValue();

            //var myDate = new Date(datefrom);
            //var from = myDate.toLocaleString()

            //var myDate1 = new Date(dateto);
            //var to = myDate1.toLocaleString()

            var passed_params = ObjId + "," + attention

            if (attention == null) {
                alert('Please Enter Attention to!');
                return;
            }

            var link = '@Url.Action("ReportViewPartial", "Subjects", new { reportParams = "_reportParams_" })';

            link.replace("_reportParams_", passed_params);
            window.open(link.replace("_reportParams_", passed_params), '_blank');

        }


        //Subjects Menu Buttons
        function OnSubjectsMenuClick(s, e) {
            //alert("I am here: So ya clicked he button over yonder then: " + e.item.name)
            //https://documentation.devexpress.com/#AspNet/DevExpressWebScriptsASPxClientGridView_UpdateEdittopic
            if (e.item.name == "btnHeaderNew") {
                var index = SubjectsGridViewPartial.GetFocusedRowIndex();
                SubjectsGridViewPartial.AddNewRow(index);
                // call edit funtion from custom button
            }

            if (e.item.name == "btnHeaderEdit") {
                var index = SubjectsGridViewPartial.GetFocusedRowIndex();
                //  alert('index : ' + index);
                SubjectsGridViewPartial.StartEditRow(index);
                // call edit funtion from custom button 
            }

            if (e.item.name == "btnHeaderDelete") {
            if (confirm("Confirm Delete?")) {
                var index = SubjectsGridViewPartial.GetFocusedRowIndex();
                SubjectsGridViewPartial.DeleteRow(index);
            }
        }

            if (e.item.name == "btnHeaderTurtorials") {
                TurtorialsLandingPopUp.Show();
            }

            if (e.item.name == "btnHeaderExams") {
                ExamsLandingPopUp.Show();
            }

            if (e.item.name == "btnPrintReport") {

                ReportOptions.Show();
            }
            
        }
    </script>
    @Html.DevExpress().FormLayout(settings =>
{
    settings.Name = "SubjectLayOut";
    settings.AlignItemCaptionsInAllGroups = true;
    settings.Width = System.Web.UI.WebControls.Unit.Percentage(100);

    var SubjectsHeader = settings.Items.AddGroupItem(groupSettings =>
    {
        // groupSettings.Caption = string.Format("Transmission Files To Process");
        groupSettings.Caption = "Subjects";
        groupSettings.ShowCaption = DefaultBoolean.True;
        groupSettings.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
        groupSettings.SettingsItemCaptions.HorizontalAlign = FormLayoutHorizontalAlign.Left;
        groupSettings.ColCount = 1;
    });

    SubjectsHeader.Items.Add(itemSettings =>
    {
        itemSettings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        itemSettings.ShowCaption = DefaultBoolean.False;
        itemSettings.ColSpan = 1;
        itemSettings.SetNestedContent(() =>
        {
            @Html.RenderAction("SubjectsGridViewPartial");
        });
    });

    SubjectsHeader.Items.Add(itemSettings =>
    {
        itemSettings.Width = System.Web.UI.WebControls.Unit.Percentage(100);
        itemSettings.ShowCaption = DefaultBoolean.False;
        itemSettings.ColSpan = 1;
        itemSettings.SetNestedContent(() =>
        {
            @Html.RenderPartial("SubjectsMenu");
        });
    });

}).GetHtml()

    @Html.DevExpress().PopupControl(settings =>
{
    settings.Name = "TurtorialsLandingPopUp";
    settings.ClientSideEvents.BeginCallback = "OnBeginCallback";
    settings.CallbackRouteValues = new { Controller = "Subjects", Action = "TurtorialsLanding" };
    settings.LoadContentViaCallback = LoadContentViaCallback.OnFirstShow;
    settings.CloseAction = CloseAction.CloseButton;
    settings.Width = Unit.Pixel(700);
    settings.Height = Unit.Pixel(500);
    settings.ShowCloseButton = true;
    settings.ShowHeader = true;
    settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
    settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
    settings.AllowDragging = true;
    settings.DragElement = DragElement.Header;
    settings.AllowResize = true;
    settings.Modal = true;
    settings.ResizingMode = ResizingMode.Live;
    settings.ShowSizeGrip = ShowSizeGrip.True;
    settings.CloseAction = CloseAction.CloseButton;
    settings.PopupAction = PopupAction.LeftMouseClick;
    settings.HeaderText = "Turtorials";
    settings.ShowCloseButton = true;

    settings.SetContent(() =>
    {
        //       @Html.RenderAction("TurtorialsLanding");

    });

}).GetHtml()

    @*@Html.DevExpress().PopupControl(settings =>
{
    settings.Name = "ExamsLandingPopUp";
    settings.ClientSideEvents.BeginCallback = "OnBeginCallback";
    settings.CallbackRouteValues = new { Controller = "Subjects", Action = "ExamsLanding" };
    settings.LoadContentViaCallback = LoadContentViaCallback.OnFirstShow;
    settings.CloseAction = CloseAction.CloseButton;
    settings.Width = Unit.Pixel(1300);
    settings.Height = Unit.Pixel(800);
    settings.ShowCloseButton = true;
    settings.ShowHeader = true;
    settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
    settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
    settings.AllowDragging = true;
    settings.DragElement = DragElement.Header;
    settings.AllowResize = true;
    settings.Modal = true;
    settings.ResizingMode = ResizingMode.Live;
    settings.ShowSizeGrip = ShowSizeGrip.True;
    settings.CloseAction = CloseAction.CloseButton;
    settings.PopupAction = PopupAction.LeftMouseClick;
    settings.HeaderText = "Exam Papers";
    settings.ShowCloseButton = true;

    settings.SetContent(() =>
    {
       //       @Html.RenderAction("TurtorialsLanding");

    });

}).GetHtml()*@

    @Html.DevExpress().PopupControl(settings =>
{
    settings.Name = "ReportOptions";
    settings.CloseAction = CloseAction.CloseButton;
    settings.Width = Unit.Pixel(200);
    settings.Height = Unit.Pixel(250);
    settings.ShowCloseButton = true;
    settings.ShowHeader = true;
    settings.PopupHorizontalAlign = PopupHorizontalAlign.WindowCenter;
    settings.PopupVerticalAlign = PopupVerticalAlign.WindowCenter;
    settings.AllowDragging = true;
    settings.DragElement = DragElement.Header;
    settings.AllowResize = true;
    settings.Modal = true;
    settings.ResizingMode = ResizingMode.Live;
    settings.ShowSizeGrip = ShowSizeGrip.True;
    settings.CloseAction = CloseAction.CloseButton;
    settings.PopupAction = PopupAction.LeftMouseClick;
    settings.HeaderText = "Report Options";
    settings.ShowCloseButton = true;

    settings.SetContent(() =>
    {

        @Html.RenderPartial("ReportOptions");

    });

}).GetHtml()
}

ConnectApp/Views/Subjects/ReportOptions.cshtml
@model ConnectApp.Models.ReportOtion



@Html.DevExpress().FormLayout(formSettings =>
{
    formSettings.Name = "ReportformLayout";
    formSettings.AlignItemCaptionsInAllGroups = true;
    formSettings.ColCount = 1;

    var infoGroupItem1 = formSettings.Items.AddGroupItem(settings =>
    {
        settings.Caption = "Please Provide the following";
        //settings.RowSpan = 2;
        settings.ShowCaption = DefaultBoolean.True;
        settings.ColCount = 1;


    });

    infoGroupItem1.Items.Add(i => i.Attention, itemSettings =>
    {

    });

    //var infoGroupItem2 = formSettings.Items.AddGroupItem(settings =>
    //{
    //    settings.Caption = "Date of Burial";
    //    //settings.RowSpan = 2;
    //    settings.ShowCaption = DefaultBoolean.True;
    //    settings.ColCount = 1;


    //});

    //infoGroupItem2.Items.Add(i => i.DateFrom, itemSettings =>
    //{
    //});

    //infoGroupItem2.Items.Add(i => i.DateTo, itemSettings =>
    //{


    //});

    var ButtonsGroupItem = formSettings.Items.AddGroupItem(Buttonsettings =>
    {
        // Buttonsettings.Caption = "";
        //settings.RowSpan = 2;
        Buttonsettings.GroupBoxDecoration = GroupBoxDecoration.None;
        Buttonsettings.ShowCaption = DefaultBoolean.False;
        Buttonsettings.ColCount = 1;
    });

    ButtonsGroupItem.Items.Add(Buttonsettings =>
    {
        Buttonsettings.ShowCaption = DefaultBoolean.False;
        Buttonsettings.SetNestedContent(() =>
        {
            Html.ViewContext.Writer.Write("<div style='float:right'>");
            Html.DevExpress().Button(btnSettings =>
            {
                btnSettings.Name = "btnPrint";
                btnSettings.Text = "Print";
                btnSettings.ClientSideEvents.Click = "PrintReport";
            }).Render();

            //Html.DevExpress().Button(btnSettings =>
            //{
            //    btnSettings.Name = "btnCancel";
            //    btnSettings.Text = "Cancel";
            //    btnSettings.Style[HtmlTextWriterStyle.MarginLeft] = "5px";
            //    btnSettings.ClientSideEvents.Click = "function (s,e) {Q67ReportOptions.Hide();}";
            //    btnSettings.UseSubmitBehavior = true;
            //}).Render();

            Html.ViewContext.Writer.Write("</div>");

        });
    });

}).GetHtml()

ConnectApp/Views/Subjects/ReportPartialView.cshtml
@*@{
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}*@
@model DevExpress.XtraReports.UI.XtraReport

@section HeadResources {
    @Html.DevExpress().GetStyleSheets(
       new StyleSheet { ExtensionType = ExtensionType.Panel },
       new StyleSheet { ExtensionType = ExtensionType.WebDocumentViewer },
       new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
       new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }

    )
    @Html.DevExpress().GetScripts(
        new Script { ExtensionType = ExtensionType.Panel },
        new Script { ExtensionType = ExtensionType.WebDocumentViewer },
        new Script { ExtensionSuite = ExtensionSuite.Report },
        new Script { ExtensionSuite = ExtensionSuite.Editors }
    )
}


@Html.DevExpress().WebDocumentViewer(settings =>
{
    settings.Name = "WebDocumentViewer";

}).Bind(Model).GetHtml()

ConnectApp/Views/Subjects/ReportViewPartial.cshtml
@model DevExpress.XtraReports.UI.XtraReport

@Html.DevExpress().GetStyleSheets(
        new StyleSheet { ExtensionType = ExtensionType.WebDocumentViewer },
        new StyleSheet { ExtensionType = ExtensionType.ReportDesigner }
    )

@Html.DevExpress().GetScripts(
        new Script { ExtensionType = ExtensionType.WebDocumentViewer },
        new Script { ExtensionType = ExtensionType.ReportDesigner }
)

@Html.DevExpress().WebDocumentViewer(settings =>
{
    settings.Name = "WebDocumentViewer";

}).Bind(Model).GetHtml()

ConnectApp/Views/Subjects/SubjectsMenu.cshtml
@* Menu Header *@
<div style="padding-bottom: 10px; float: right;">
    @Html.DevExpress().Menu(settings =>
{
    string UserRole = Session["UserRole"].ToString();

    var GetUserRole = UserRole == "Admin" ? "true" : "false";

    bool isEdit = bool.Parse(GetUserRole);

    settings.Name = "SubjectsMenu";
    settings.ShowAsToolbar = true;
    settings.ShowPopOutImages = DefaultBoolean.True;
    if (isEdit == true)
    {
        settings.Items.Add("New", "btnHeaderNew");
        settings.Items.Add("Edit", "btnHeaderEdit");
        settings.Items.Add("Delete", "btnHeaderDelete");
    }
    settings.Items.Add("Learn", "btnHeaderTurtorials");
    //   settings.Items.Add("Exam Papers", "btnHeaderExams");

    if (isEdit == true)
    {
        settings.Items.Add("Print", "btnPrintReport");
    }
    settings.ClientSideEvents.ItemClick = "OnSubjectsMenuClick";
}).GetHtml()

</div>

ConnectApp/Views/Subjects/TurtorialsLanding.cshtml
@using (Html.BeginForm())
{
<html>
<body>

    @*<iframe height="575" width="900" src="~/Content/Presentations/Learn1.pdf#page=2"></iframe>*@
   
    @*<iframe src="\Content\Videos\accounting_ethics.mp4" frameborder="0" width="900" height="575" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>*@

    @*<embed src="~\Content\Videos\accounting_ethics.mp4" autostart="false" height="575" width="900" />*@

    <embed src="\Content\Videos\accounting_ethics.mp4" autostart="false" height="575" width="900" />

 </body>
</html>
}

ConnectApp/Views/Subjects/_SubjectsGridViewPartial.cshtml
@using DevExpress.Web;
@using DevExpress.Web.Mvc;
@using ConnectApp.Helpers;



@Html.DevExpress().GridView(
    settings =>
    {
        //  string UserRole = Session["UserRole"].ToString();

        //   var GetUserRole = UserRole == "Admin" ? "true" : "false";

        //   bool isEdit = bool.Parse(GetUserRole);


        settings.Name = "SubjectsGridViewPartial";
        Html.PalBrokerHtml().GridView.GridDefaultBehavior(settings, "SubjectsGridViewPartial");

        settings.CallbackRouteValues = new { Controller = "Subjects", Action = "SubjectsGridViewPartial" };

        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "Subjects", Action = "SubjectsAddEdit" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Subjects", Action = "SubjectsAddEdit" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "Subjects", Action = "SubjectsDelete" };
        settings.Width = Unit.Percentage(100);
        //settings.Settings.VerticalScrollBarMode = ScrollBarMode.Auto;
        //  settings.Settings.VerticalScrollableHeight = 510;
        settings.Settings.ShowGroupPanel = true;
        settings.Settings.ShowFilterRow = true;
        settings.Settings.ShowFilterRowMenu = true;
        settings.SettingsBehavior.AllowFocusedRow = true;

        settings.SettingsBehavior.ConfirmDelete = true;
        settings.SettingsEditing.Mode = GridViewEditingMode.PopupEditForm; // POPUP EDIT FORM
        settings.SettingsPopup.EditForm.Modal = true;
        settings.SettingsBehavior.ConfirmDelete = true;

        settings.SettingsPopup.EditForm.VerticalAlign = PopupVerticalAlign.WindowCenter;
        settings.SettingsPopup.EditForm.HorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.SettingsPopup.EditForm.ShowHeader = true;

        settings.KeyFieldName = "ObjId";
        settings.Columns.Add(column => { column.FieldName = "LanguageName"; column.Caption = "Language";});
        settings.Columns.Add(column => { column.FieldName = "Description"; column.Caption = "Description"; });

        //if (isEdit == true)
        //{
        settings.Columns.Add(column =>
        {
            column.FieldName = "Link";
            column.Caption = "Link";
            column.ColumnType = MVCxGridViewColumnType.HyperLink;
            var hyperLinkProperties = column.PropertiesEdit as HyperLinkProperties;
            column.Width = Unit.Pixel(720);
        });
        //}

        //settings.Columns.Add(column =>
        //{
        //    column.FieldName = "ExamPaperLink";
        //    column.Caption = "Exam Paper";
        //    column.ColumnType = MVCxGridViewColumnType.HyperLink;
        //    var hyperLinkProperties = column.PropertiesEdit as HyperLinkProperties;
        //    column.Width = Unit.Pixel(520);
        //});
        // }

        settings.SetEditFormTemplateContent(c =>
        {

            ViewContext.Writer.Write((Html.Action("EditHeaderFormPartial", new { ObjId = c.KeyValue != null ? c.KeyValue.ToString() : Guid.NewGuid().ToString() }).ToHtmlString()));
        });

        //settings.BeforeGetCallbackResult = (s, e) =>

        //{
        //    var gridview = s as mvcxgridview;
        //    var doc = gridview.editingrowvisibleindex > 0 ? gridview.getrowvalues(gridview.editingrowvisibleindex, "subjectname").tostring() : "";
        //    gridview.settingstext.popupeditformcaption = "edit : " + doc;

        //    if (gridview.isnewrowediting)
        //    {
        //        gridview.settingstext.popupeditformcaption = "new subject";

        //    }
        //};


        settings.SettingsPager.PageSizeItemSettings.Visible = true;
        settings.SettingsPager.AlwaysShowPager = true;

        settings.ClientSideEvents.ColumnResized = "HighlightEllipsis";
        settings.SettingsBehavior.AllowEllipsisInText = true;

        settings.ControlStyle.Wrap = DefaultBoolean.False;
        //settings.Settings.HorizontalScrollBarMode = ScrollBarMode.Auto;
        settings.ClientSideEvents.FocusedRowChanged = "OnSubjectsHeaderGridFocusedRowChanged";
        settings.ClientSideEvents.Init = "function(s, e) { s.PerformCallback(); }";
        settings.ClientSideEvents.EndCallback = "InitialSetFocus";

        settings.Settings.ShowHeaderFilterButton = true;
        settings.SettingsPopup.HeaderFilter.Height = 250;
        var headerFilterMode = GridHeaderFilterMode.CheckedList;
        foreach (GridViewDataColumn column in settings.Columns)
            column.SettingsHeaderFilter.Mode = headerFilterMode;
    }).SetEditErrorText(ViewData["EditError"] != null ? (string)ViewData["EditError"] : string.Empty).Bind(Model).GetHtml()